name: Documentation Request
description: Create an issue for missing or incorrect documentation
title: "[Documentation]: "
labels: ["Type:Docs","Status: Unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Tell us where what you would like to see get added to the documentation or if there is an error in the documentation?

  - type: textarea
    id: what-happened
    attributes:
      label: Summary
      placeholder: Description of what you would like to see
    validations:
      required: true
